users:
  - github: Taucher2003
    gitlab: Taucher2003
    discord: "444889694002741249"

  - github: nicosammito
    gitlab: nicosammito
    discord: "456437986238791701"

  - github: raphael-goetz
    gitlab: raphael.goetz.7
    discord: "329279009298841600"

  - github: Knerio
    gitlab: knerio
    discord: "639416958923702292"

  - github: mvriu5
    discord: "388405725929406472"

  - github: 1chroniks
    discord: "572808505304809502"

  - github: Nicuschgifthub
    discord: "380808844093292555"

  - github: code0-release-tools[bot]
    gitlab: code0-release-tools
    discord: "1465083247296905299"
