.chatops:
  image: ruby:3.2.2
  stage: chatops
  timeout: 10 min
  script:
    - bundle install
    - bin/chatops $CI_JOB_NAME $CHAT_INPUT
  variables:
    THOR_SHELL: 'Basic'
  rules:
    - if: $CI_PIPELINE_SOURCE == "chat"

components:
  extends: .chatops
